AllCops:
  Exclude:
    - 'Rakefile'

Layout/LineLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/GuardClause:
  Exclude:
    - 'thumper.gemspec'

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Semicolon:
  Enabled: false
